In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("retail_sales_analysis_dataset_friend.csv")

In [3]:
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Region,City,Category,Product,Quantity,Unit_Price,Discount,Payment_Mode,Customer_Type,Returned,Revenue,Discount_Amount,Final_Sales
0,ORD300001,2025-03-27,CUST13421,Customer_13421,East,Vijayawada,Electronics,Smart Watch,2,10911.02,0.05,Debit Card,Returning,No,21822.04,1091.1020,20730.9380
1,ORD300002,2024-06-06,CUST12647,Customer_12647,North,Kolkata,Furniture,Sofa,3,10544.55,0.05,Cash,Returning,No,31633.65,1581.6825,30051.9675
2,ORD300003,2024-07-03,CUST12597,Customer_12597,South,Hyderabad,Home & Kitchen,Mixer Grinder,6,1242.14,0.05,Credit Card,Returning,No,7452.84,372.6420,7080.1980
3,ORD300004,2025-09-14,CUST13403,Customer_13403,North,Hyderabad,Clothing,Jeans,3,1620.36,0.00,Credit Card,Returning,No,4861.08,0.0000,4861.0800
4,ORD300005,2025-07-20,CUST12586,Customer_12586,East,Bengaluru,Sports,Yoga Mat,5,7564.48,0.15,UPI,Returning,No,37822.40,5673.3600,32149.0400

In [4]:
df.tail()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Region,City,Category,Product,Quantity,Unit_Price,Discount,Payment_Mode,Customer_Type,Returned,Revenue,Discount_Amount,Final_Sales
4995,ORD304996,2024-03-31,CUST13438,Customer_13438,North,Kolkata,Sports,Football,6,1483.18,0.05,Cash,Returning,No,8899.08,444.954,8454.126
4996,ORD304997,2025-04-02,CUST12644,Customer_12644,South,Bengaluru,Clothing,Sneakers,6,1109.56,0.15,Debit Card,Returning,No,6657.36,998.604,5658.756
4997,ORD304998,2025-07-27,CUST12907,Customer_12907,East,Hyderabad,Electronics,USB Keyboard,2,5655.10,0.05,Net Banking,New,No,11310.20,565.510,10744.690
4998,ORD304999,2025-04-27,CUST12800,Customer_12800,West,Pune,Clothing,Formal Shirt,2,2187.03,0.10,Credit Card,Returning,No,4374.06,437.406,3936.654
4999,ORD305000,2024-09-06,CUST12355,Customer_12355,South,Chennai,Electronics,USB Keyboard,4,4531.79,0.15,Debit Card,New,No,18127.16,2719.074,15408.086

In [5]:
df.shape

(5000, 17)

In [6]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Name', 'Region',
       'City', 'Category', 'Product', 'Quantity', 'Unit_Price', 'Discount',
       'Payment_Mode', 'Customer_Type', 'Returned', 'Revenue',
       'Discount_Amount', 'Final_Sales'],
      dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         5000 non-null   str
 1   Order_Date       5000 non-null   str
 2   Customer_ID      5000 non-null   str
 3   Customer_Name    5000 non-null   str
 4   Region           5000 non-null   str
 5   City             4975 non-null   str
 6   Category         5000 non-null   str
 7   Product          5000 non-null   str
 8   Quantity         5000 non-null   int64
 9   Unit_Price       5000 non-null   float64
 10  Discount         4985 non-null   float64
 11  Payment_Mode     5000 non-null   str
 12  Customer_Type    5000 non-null   str
 13  Returned         5000 non-null   str
 14  Revenue          5000 non-null   float64
 15  Discount_Amount  5000 non-null   float64
 16  Final_Sales      5000 non-null   float64
dtypes: float64(5), int64(1), str(11)
memory usage: 664.2 KB

In [8]:
df.describe()

,Quantity,Unit_Price,Discount,Revenue,Discount_Amount,Final_Sales
count,5000.000000,5000.000000,4985.000000,5000.000000,5000.000000,5000.000000
mean,2.797400,8345.115344,0.090381,23333.947436,2117.751773,21216.195663
std,1.654963,6882.958054,0.067117,25978.013048,3368.599410,23646.472797
min,1.000000,375.240000,0.000000,436.550000,0.000000,384.880000
25%,1.000000,3206.560000,0.050000,6327.380000,212.841625,5723.446125
50%,2.000000,5924.055000,0.100000,14644.085000,917.198500,13265.152500
75%,4.000000,11127.477500,0.150000,29844.140000,2519.209125,27246.839750
max,7.000000,28974.720000,0.250000,182269.780000,36453.956000,162982.389500

In [9]:
df.describe(include="object")

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_5052\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,Order_ID,Order_Date,Customer_ID,Customer_Name,Region,City,Category,Product,Payment_Mode,Customer_Type,Returned
count,5000,5000,5000,5000,5000,4975,5000,5000,5000,5000,5000
unique,5000,730,1453,1453,4,8,5,25,5,2,2
top,ORD300001,2025-02-10,CUST12310,Customer_12310,South,Mumbai,Clothing,Coffee Table,Net Banking,Returning,No
freq,1,17,12,12,1297,668,1019,224,1025,3059,4523

In [10]:
df.isnull().sum()

Order_ID            0
Order_Date          0
Customer_ID         0
Customer_Name       0
Region              0
City               25
Category            0
Product             0
Quantity            0
Unit_Price          0
Discount           15
Payment_Mode        0
Customer_Type       0
Returned            0
Revenue             0
Discount_Amount     0
Final_Sales         0
dtype: int64

In [11]:
(df.isnull().sum() / len(df)) * 100

Order_ID           0.0
Order_Date         0.0
Customer_ID        0.0
Customer_Name      0.0
Region             0.0
City               0.5
Category           0.0
Product            0.0
Quantity           0.0
Unit_Price         0.0
Discount           0.3
Payment_Mode       0.0
Customer_Type      0.0
Returned           0.0
Revenue            0.0
Discount_Amount    0.0
Final_Sales        0.0
dtype: float64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df["Region"].unique()

<StringArray>
['East', 'North', 'South', 'West']
Length: 4, dtype: str

In [14]:
df["Region"].nunique()

4

In [15]:
df["City"] = df["City"].fillna("Unknown")

In [16]:
df["Discount"] = df["Discount"].fillna(0)

In [17]:
df.isnull().sum()

Order_ID           0
Order_Date         0
Customer_ID        0
Customer_Name      0
Region             0
City               0
Category           0
Product            0
Quantity           0
Unit_Price         0
Discount           0
Payment_Mode       0
Customer_Type      0
Returned           0
Revenue            0
Discount_Amount    0
Final_Sales        0
dtype: int64

In [18]:
df = df.drop_duplicates()

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

In [21]:
df["Order_Date"].dtype

dtype('<M8[us]')

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         5000 non-null   str
 1   Order_Date       5000 non-null   datetime64[us]
 2   Customer_ID      5000 non-null   str
 3   Customer_Name    5000 non-null   str
 4   Region           5000 non-null   str
 5   City             5000 non-null   str
 6   Category         5000 non-null   str
 7   Product          5000 non-null   str
 8   Quantity         5000 non-null   int64
 9   Unit_Price       5000 non-null   float64
 10  Discount         5000 non-null   float64
 11  Payment_Mode     5000 non-null   str
 12  Customer_Type    5000 non-null   str
 13  Returned         5000 non-null   str
 14  Revenue          5000 non-null   float64
 15  Discount_Amount  5000 non-null   float64
 16  Final_Sales      5000 non-null   float64
dtypes: datetime64[us](1), float64(5), int64(1), str(10)
memory usage: 664.2 KB

In [23]:
df["Revenue"] = (
    df["Quantity"] * df["Unit_Price"]
)

In [24]:
df[["Quantity", "Unit_Price", "Revenue"]].head()

   Quantity  Unit_Price   Revenue
0         2    10911.02  21822.04
1         3    10544.55  31633.65
2         6     1242.14   7452.84
3         3     1620.36   4861.08
4         5     7564.48  37822.40

In [25]:
df["Discount_Amount"] = (
    df["Revenue"] * df["Discount"]
)

In [26]:
df["Final_Sales"] = (
    df["Revenue"] - df["Discount_Amount"]
)

In [27]:
df[
    [
        "Quantity",
        "Unit_Price",
        "Revenue",
        "Discount",
        "Discount_Amount",
        "Final_Sales"
    ]
].head()

   Quantity  Unit_Price   Revenue  Discount  Discount_Amount  Final_Sales
0         2    10911.02  21822.04      0.05        1091.1020   20730.9380
1         3    10544.55  31633.65      0.05        1581.6825   30051.9675
2         6     1242.14   7452.84      0.05         372.6420    7080.1980
3         3     1620.36   4861.08      0.00           0.0000    4861.0800
4         5     7564.48  37822.40      0.15        5673.3600   32149.0400

In [28]:
total_sales = df["Final_Sales"].sum()

total_sales

np.float64(106080978.31400001)

In [29]:
number_of_orders = df["Order_ID"].nunique()

number_of_orders

5000

In [30]:
number_of_orders = df["Order_ID"].nunique()

number_of_orders

5000

In [31]:
aov = total_sales / number_of_orders

aov

np.float64(21216.1956628)

In [32]:
sales_by_region = (
    df.groupby("Region")["Final_Sales"]
      .sum()
)

sales_by_region

Region
East     2.602908e+07
North    2.633009e+07
South    2.741399e+07
West     2.630782e+07
Name: Final_Sales, dtype: float64

In [33]:
sales_by_region.sort_values(
    ascending=False
)

Region
South    2.741399e+07
North    2.633009e+07
West     2.630782e+07
East     2.602908e+07
Name: Final_Sales, dtype: float64

In [34]:
quantity_by_region = (
    df.groupby("Region")["Quantity"]
      .sum()
)

quantity_by_region

Region
East     3551
North    3413
South    3563
West     3460
Name: Quantity, dtype: int64

In [35]:
sales_by_category = (
    df.groupby("Category")["Final_Sales"]
      .sum()
)

sales_by_category

Category
Clothing          7.668862e+06
Electronics       3.206763e+07
Furniture         3.875535e+07
Home & Kitchen    1.500075e+07
Sports            1.258839e+07
Name: Final_Sales, dtype: float64

In [36]:
sales_by_category.sort_values(
    ascending=False
)

Category
Furniture         3.875535e+07
Electronics       3.206763e+07
Home & Kitchen    1.500075e+07
Sports            1.258839e+07
Clothing          7.668862e+06
Name: Final_Sales, dtype: float64

In [37]:
quantity_by_category = (
    df.groupby("Category")["Quantity"]
      .sum()
)

quantity_by_category

Category
Clothing          2772
Electronics       2864
Furniture         2792
Home & Kitchen    2743
Sports            2816
Name: Quantity, dtype: int64

In [38]:
product_sales.sort_values(
    ascending=False
).head(10)

NameError: name 'product_sales' is not defined

In [39]:
product_sales = (
    df.groupby("Product")["Final_Sales"]
      .sum()
)

In [40]:
product_sales.sort_values(
    ascending=False
).head(10)

Product
Study Table            8.812920e+06
Coffee Table           8.094066e+06
Sofa                   7.540987e+06
Office Chair           7.370356e+06
Bookshelf              6.937019e+06
Power Bank             6.905862e+06
Smart Watch            6.893337e+06
Bluetooth Speaker      6.693276e+06
Wireless Headphones    5.892836e+06
USB Keyboard           5.682314e+06
Name: Final_Sales, dtype: float64

In [41]:
product_sales.sort_values(
    ascending=False
).head(10)

Product
Study Table            8.812920e+06
Coffee Table           8.094066e+06
Sofa                   7.540987e+06
Office Chair           7.370356e+06
Bookshelf              6.937019e+06
Power Bank             6.905862e+06
Smart Watch            6.893337e+06
Bluetooth Speaker      6.693276e+06
Wireless Headphones    5.892836e+06
USB Keyboard           5.682314e+06
Name: Final_Sales, dtype: float64

In [42]:
payment_sales = (
    df.groupby("Payment_Mode")["Final_Sales"]
      .sum()
      .sort_values(ascending=False)
)

payment_sales

Payment_Mode
UPI            2.179063e+07
Net Banking    2.175427e+07
Credit Card    2.172357e+07
Cash           2.070681e+07
Debit Card     2.010570e+07
Name: Final_Sales, dtype: float64

In [43]:
orders_by_payment = (
    df.groupby("Payment_Mode")["Order_ID"]
      .nunique()
)

orders_by_payment

Payment_Mode
Cash            978
Credit Card     991
Debit Card      982
Net Banking    1025
UPI            1024
Name: Order_ID, dtype: int64

In [44]:
sales_by_customer_type = (
    df.groupby("Customer_Type")["Final_Sales"]
      .sum()
)

sales_by_customer_type

Customer_Type
New          4.170260e+07
Returning    6.437838e+07
Name: Final_Sales, dtype: float64

In [45]:
orders_by_customer_type = (
    df.groupby("Customer_Type")["Order_ID"]
      .nunique()
)

orders_by_customer_type

Customer_Type
New          1941
Returning    3059
Name: Order_ID, dtype: int64

In [46]:
customer_analysis = df.groupby(
    "Customer_Type"
).agg(
    Total_Sales=("Final_Sales", "sum"),
    Orders=("Order_ID", "nunique")
)

In [47]:
customer_analysis["AOV"] = (
    customer_analysis["Total_Sales"] /
    customer_analysis["Orders"]
)

customer_analysis

                Total_Sales  Orders           AOV
Customer_Type
New            4.170260e+07    1941  21485.111866
Returning      6.437838e+07    3059  21045.562662

In [48]:
customer_sales = (
    df.groupby(
        ["Customer_ID", "Customer_Name"]
    )["Final_Sales"]
    .sum()
)

In [49]:
customer_sales.sort_values(
    ascending=False
).head(10)

Customer_ID  Customer_Name
CUST13462    Customer_13462    361491.9020
CUST12267    Customer_12267    337950.5205
CUST12771    Customer_12771    337519.4100
CUST12115    Customer_12115    317243.0620
CUST12310    Customer_12310    308666.3240
CUST13450    Customer_13450    304945.7720
CUST12390    Customer_12390    299346.1015
CUST12748    Customer_12748    294111.9590
CUST12096    Customer_12096    275544.1455
CUST12079    Customer_12079    274741.0635
Name: Final_Sales, dtype: float64

In [50]:
category_analysis = df.groupby(
    "Category"
).agg(
    Total_Sales=("Final_Sales", "sum"),
    Total_Quantity=("Quantity", "sum"),
    Number_of_Orders=("Order_ID", "nunique")
)

category_analysis

                 Total_Sales  Total_Quantity  Number_of_Orders
Category
Clothing        7.668862e+06            2772              1019
Electronics     3.206763e+07            2864              1001
Furniture       3.875535e+07            2792               990
Home & Kitchen  1.500075e+07            2743               973
Sports          1.258839e+07            2816              1017

In [51]:
df["Year"] = df["Order_Date"].dt.year

In [52]:
df["Month"] = df["Order_Date"].dt.month

In [53]:
df["Month_Name"] = (
    df["Order_Date"].dt.month_name()
)

In [54]:
df["Quarter"] = (
    df["Order_Date"].dt.quarter
)

In [55]:
yearly_sales = (
    df.groupby("Year")["Final_Sales"]
      .sum()
)

yearly_sales

Year
2024    5.329226e+07
2025    5.278871e+07
Name: Final_Sales, dtype: float64

In [56]:
yearly_sales = (
    df.groupby("Year")["Final_Sales"]
      .sum()
)

yearly_sales

Year
2024    5.329226e+07
2025    5.278871e+07
Name: Final_Sales, dtype: float64

In [57]:
yearly_quantity = (
    df.groupby("Year")["Quantity"]
      .sum()
)

yearly_quantity

Year
2024    7112
2025    6875
Name: Quantity, dtype: int64

In [58]:
yearly_orders = (
    df.groupby("Year")["Order_ID"]
      .nunique()
)

yearly_orders

Year
2024    2515
2025    2485
Name: Order_ID, dtype: int64

In [59]:
yearly_analysis = df.groupby(
    "Year"
).agg(
    Sales=("Final_Sales", "sum"),
    Orders=("Order_ID", "nunique")
)

yearly_analysis["AOV"] = (
    yearly_analysis["Sales"] /
    yearly_analysis["Orders"]
)

yearly_analysis

             Sales  Orders           AOV
Year
2024  5.329226e+07    2515  21189.766800
2025  5.278871e+07    2485  21242.943586

In [60]:
monthly_sales = (
    df.groupby("Month")["Final_Sales"]
      .sum()
)

monthly_sales

Month
1     8.896340e+06
2     8.769287e+06
3     9.191443e+06
4     8.905558e+06
5     9.391676e+06
6     9.037433e+06
7     8.986287e+06
8     8.558299e+06
9     9.241388e+06
10    8.103694e+06
11    8.649154e+06
12    8.350418e+06
Name: Final_Sales, dtype: float64

In [61]:
monthly_quantity = (
    df.groupby("Month")["Quantity"]
      .sum()
)

monthly_quantity

Month
1     1026
2     1133
3     1314
4     1187
5     1236
6     1250
7     1213
8     1171
9     1203
10    1051
11    1078
12    1125
Name: Quantity, dtype: int64

In [62]:
monthly_orders = (
    df.groupby("Month")["Order_ID"]
      .nunique()
)

monthly_orders

Month
1     392
2     416
3     450
4     424
5     443
6     451
7     423
8     422
9     410
10    376
11    387
12    406
Name: Order_ID, dtype: int64

In [63]:
monthly_analysis = df.groupby(
    "Month"
).agg(
    Sales=("Final_Sales", "sum"),
    Orders=("Order_ID", "nunique"),
    Quantity=("Quantity", "sum")
)

In [64]:
monthly_analysis["AOV"] = (
    monthly_analysis["Sales"] /
    monthly_analysis["Orders"]
)

monthly_analysis

              Sales  Orders  Quantity           AOV
Month
1      8.896340e+06     392      1026  22694.745019
2      8.769287e+06     416      1133  21080.017731
3      9.191443e+06     450      1314  20425.428177
4      8.905558e+06     424      1187  21003.673527
5      9.391676e+06     443      1236  21200.172512
6      9.037433e+06     451      1250  20038.653899
7      8.986287e+06     423      1213  21244.177916
8      8.558299e+06     422      1171  20280.328797
9      9.241388e+06     410      1203  22539.971944
10     8.103694e+06     376      1051  21552.378416
11     8.649154e+06     387      1078  22349.235475
12     8.350418e+06     406      1125  20567.532962

In [65]:
monthly_analysis["Sales_Change"] = (
    monthly_analysis["Sales"].diff()
)

In [66]:
monthly_analysis["MoM_Growth_%"] = (
    monthly_analysis["Sales"].pct_change() * 100
)

In [67]:
monthly_analysis["Order_Growth_%"] = (
    monthly_analysis["Orders"].pct_change() * 100
)

In [68]:
monthly_analysis["Quantity_Growth_%"] = (
    monthly_analysis["Quantity"].pct_change() * 100
)

In [69]:
monthly_analysis.coloumns

AttributeError: 'DataFrame' object has no attribute 'coloumns'

In [70]:
monthly_analysis.columns

Index(['Sales', 'Orders', 'Quantity', 'AOV', 'Sales_Change', 'MoM_Growth_%',
       'Order_Growth_%', 'Quantity_Growth_%'],
      dtype='str')

In [71]:
monthly_analysis.sort_values(
    "Sales",
    ascending=False
).head(1)

,Sales,Orders,Quantity,AOV,Sales_Change,MoM_Growth_%,Order_Growth_%,Quantity_Growth_%
Month,,,,,,,,
5,9391676.423,443,1236,21200.172512,486118.8475,5.458601,4.481132,4.128054

In [72]:
monthly_analysis.sort_values(
    "Sales",
    ascending=True
).head(1)

,Sales,Orders,Quantity,AOV,Sales_Change,MoM_Growth_%,Order_Growth_%,Quantity_Growth_%
Month,,,,,,,,
10,8.103694e+06,376,1051,21552.378416,-1.137694e+06,-12.310858,-8.292683,-12.635079

In [73]:
monthly_analysis["3_Month_Moving_Avg"] = (
    monthly_analysis["Sales"]
    .rolling(window=3)
    .mean()
)

In [74]:
quarterly_sales = (
    df.groupby(
        ["Year", "Quarter"]
    )["Final_Sales"]
    .sum()
)

quarterly_sales

Year  Quarter
2024  1          1.353455e+07
      2          1.405565e+07
      3          1.336165e+07
      4          1.234041e+07
2025  1          1.332252e+07
      2          1.327901e+07
      3          1.342432e+07
      4          1.276286e+07
Name: Final_Sales, dtype: float64

In [75]:
region_category = pd.pivot_table(
    df,
    values="Final_Sales",
    index="Region",
    columns="Category",
    aggfunc="sum"
)

region_category

Category,Clothing,Electronics,Furniture,Home & Kitchen,Sports
Region,,,,,
East,1.831908e+06,7.892132e+06,8.921730e+06,4.060317e+06,3.322989e+06
North,1.814021e+06,7.908429e+06,9.843996e+06,3.488236e+06,3.275413e+06
South,2.032179e+06,8.250776e+06,1.030387e+07,3.930914e+06,2.896258e+06
West,1.990755e+06,8.016289e+06,9.685756e+06,3.521281e+06,3.093734e+06

In [76]:
region_month = pd.pivot_table(
    df,
    values="Final_Sales",
    index="Region",
    columns="Month",
    aggfunc="sum"
)

region_month

Month,1,2,3,4,5,6,7,8,9,10,11,12
Region,,,,,,,,,,,,
East,2.447660e+06,2.385691e+06,2.439294e+06,2.474047e+06,2.167307e+06,1.646994e+06,2.025279e+06,2.555119e+06,2.589982e+06,1.759289e+06,1.782546e+06,1.755868e+06
North,1.902870e+06,1.978662e+06,2.149880e+06,1.974415e+06,2.433571e+06,2.417305e+06,2.194806e+06,2.475673e+06,1.737535e+06,2.530666e+06,2.156383e+06,2.378328e+06
South,1.954675e+06,2.262700e+06,1.968237e+06,2.156494e+06,2.563772e+06,2.678179e+06,2.765697e+06,2.104424e+06,2.384068e+06,2.002240e+06,2.594282e+06,1.979227e+06
West,2.591135e+06,2.142235e+06,2.634032e+06,2.300601e+06,2.227026e+06,2.294954e+06,2.000506e+06,1.423083e+06,2.529804e+06,1.811500e+06,2.115943e+06,2.236996e+06

In [77]:
category_month = pd.pivot_table(
    df,
    values="Final_Sales",
    index="Category",
    columns="Month",
    aggfunc="sum"
)

category_month

Month,1,2,3,4,5,6,7,8,9,10,11,12
Category,,,,,,,,,,,,
Clothing,5.418023e+05,6.009221e+05,8.126738e+05,5.672059e+05,6.347653e+05,8.417293e+05,6.910045e+05,5.932657e+05,5.935809e+05,6.338571e+05,5.516206e+05,6.064349e+05
Electronics,2.890714e+06,3.056081e+06,2.507858e+06,2.339916e+06,3.481467e+06,2.418870e+06,2.314608e+06,2.087775e+06,3.084608e+06,2.652340e+06,2.940173e+06,2.293217e+06
Furniture,3.790441e+06,3.150722e+06,2.994953e+06,3.629703e+06,2.822288e+06,3.259107e+06,3.601563e+06,3.117210e+06,3.279359e+06,2.831757e+06,3.311600e+06,2.966646e+06
Home & Kitchen,8.316675e+05,8.203051e+05,1.558663e+06,1.566672e+06,1.212792e+06,1.372670e+06,1.291677e+06,1.677275e+06,1.318197e+06,9.169797e+05,1.084255e+06,1.349594e+06
Sports,8.417154e+05,1.141258e+06,1.317295e+06,8.020609e+05,1.240364e+06,1.145057e+06,1.087434e+06,1.082773e+06,9.656446e+05,1.068760e+06,7.615054e+05,1.134527e+06

In [78]:
Q1 = df["Final_Sales"].quantile(0.25)

In [79]:
Q3 = df["Final_Sales"].quantile(0.75)

In [80]:
IQR = Q3 - Q1

In [81]:
lower_bound = Q1 - 1.5 * IQR

In [82]:
upper_bound = Q3 + 1.5 * IQR

In [83]:
upper_bound = Q3 + 1.5 * IQR

In [84]:
df.to_csv("retail_sales_analysis_cleaned.csv", index=False)